<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="fable.react.markdown.fs" />

    <!-- Global to the app -->
    <Compile Include="../Shared/ChatProtocol.fs" />
    <Compile Include="Router.fs" />

    <Compile Include="UserAvatar/View.fs" />

    <Compile Include="Channel/Types.fs" />
    <Compile Include="Channel/State.fs" />
    <Compile Include="Channel/View.fs" />

    <Compile Include="Chat/Types.fs" />
    <Compile Include="Chat/State.fs" />

    <Compile Include="Overview/View.fs" />

    <Compile Include="NavMenu/View.fs" />

    <!-- App -->
    <Compile Include="Types.fs" />
    <Compile Include="State.fs" />
    <Compile Include="App.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Fable.Core" Version="1.3.11" />
    <PackageReference Include="Fable.Elmish.React" Version="1.0.1" />
    <PackageReference Include="Fable.Elmish.Browser" Version="1.0.0" />
    <PackageReference Include="Fable.Elmish.Debugger" Version="1.0.1" />
    <PackageReference Include="Fable.Elmish.HMR" Version="1.0.0" />
    <PackageReference Include="Fable.Websockets.Client" Version="0.1.1" />
    <PackageReference Include="Fable.Websockets.Elmish" Version="0.1.1" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="dotnet-fable" Version="1.3.11" />
  </ItemGroup>
</Project>
