<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <DebugType>portable</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Selectors.fs" />
    <Compile Include="Routines.fs" />
    <Compile Include="tests/*.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Canopy" Version="2.1.5" />
    <PackageReference Include="Expecto" Version="10.2.3" />
    <PackageReference Include="Selenium.WebDriver" Version="4.16.2" />
    <PackageReference Include="WebDriverManager" Version="2.17.6" />
  </ItemGroup>
</Project>